package com.jzw.book.mapper;

import com.jzw.book.model.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_address
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_address
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_address
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_address
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    Address selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_address
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_address
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKey(Address record);
}