package com.jzw.book.mapper;

import com.jzw.book.model.Authority;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_authority
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_authority
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_authority
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_authority
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    Authority selectByPrimaryKey(Integer authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_authority
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_authority
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKey(Authority record);
}