package com.jzw.book.mapper;

import com.jzw.book.model.Images;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_images
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_images
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_images
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insertSelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_images
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    Images selectByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_images
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_images
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKey(Images record);
}