package com.jzw.book.mapper;

import com.jzw.book.model.Orders;
import com.jzw.book.util.PageBean;

import java.util.List;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    List<Orders> selectByPrimaryKey(PageBean pageBean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_orders
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKey(Orders record);
}