package com.jzw.book.mapper;

import com.jzw.book.model.Shops;

public interface ShopsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_shop
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_shop
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insert(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_shop
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insertSelective(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_shop
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    Shops selectByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_shop
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_shop
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKey(Shops record);
}