package com.jzw.book.mapper;

import com.jzw.book.model.Types;

import java.util.List;

public interface TypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_type
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_type
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insert(Types record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_type
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int insertSelective(Types record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_type
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    Types selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_type
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Types record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_type
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    int updateByPrimaryKey(Types record);


    public List<Types> showAll();

}