package com.jzw.book.model;

import javax.validation.constraints.NotBlank;
import java.io.Serializable;

public class Address implements Serializable{



    private Integer addressId;

    @NotBlank(message = "收货地址不能为空！")
    private String addressName;

    @NotBlank(message = "收货人姓名不能为空！")
    private String addressUsername;

    @NotBlank(message = "联系电话不能为空！")
    private String addressPhone;

    @NotBlank(message = "邮编不能为空！")
    private String addressCode;





    public Integer getAddressId() {
        return addressId;
    }

    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    public String getAddressName() {
        return addressName;
    }

    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.address_username
     *
     * @return the value of b_address.address_username
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getAddressUsername() {
        return addressUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.address_username
     *
     * @param addressUsername the value for b_address.address_username
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setAddressUsername(String addressUsername) {
        this.addressUsername = addressUsername == null ? null : addressUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.address_phone
     *
     * @return the value of b_address.address_phone
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getAddressPhone() {
        return addressPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.address_phone
     *
     * @param addressPhone the value for b_address.address_phone
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setAddressPhone(String addressPhone) {
        this.addressPhone = addressPhone == null ? null : addressPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_address.address_code
     *
     * @return the value of b_address.address_code
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getAddressCode() {
        return addressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_address.address_code
     *
     * @param addressCode the value for b_address.address_code
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setAddressCode(String addressCode) {
        this.addressCode = addressCode == null ? null : addressCode.trim();
    }


    @Override
    public String toString() {
        return "Address{" +
                "addressId=" + addressId +
                ", addressName='" + addressName + '\'' +
                ", addressUsername='" + addressUsername + '\'' +
                ", addressPhone='" + addressPhone + '\'' +
                ", addressCode='" + addressCode + '\'' +
                '}';
    }
}