package com.jzw.book.model;

import java.io.Serializable;

/**
 * 权限实体
 * @author Jzw
 *
 */
public class Authority implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_authority.authority_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_authority.authority_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private String authorityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_authority.authority_id
     *
     * @return the value of b_authority.authority_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_authority.authority_id
     *
     * @param authorityId the value for b_authority.authority_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_authority.authority_name
     *
     * @return the value of b_authority.authority_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_authority.authority_name
     *
     * @param authorityName the value for b_authority.authority_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }
}