package com.jzw.book.model;

import java.io.Serializable;

public class Images implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_images.img_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_images.img_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private String imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_images.book_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_images.img_id
     *
     * @return the value of b_images.img_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_images.img_id
     *
     * @param imgId the value for b_images.img_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_images.img_name
     *
     * @return the value of b_images.img_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_images.img_name
     *
     * @param imgName the value for b_images.img_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_images.book_id
     *
     * @return the value of b_images.book_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_images.book_id
     *
     * @param bookId the value for b_images.book_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}