package com.jzw.book.model;

import java.io.Serializable;

public class Roles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role.role_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_role.role_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role.role_id
     *
     * @return the value of b_role.role_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_role.role_id
     *
     * @param roleId the value for b_role.role_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_role.role_name
     *
     * @return the value of b_role.role_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_role.role_name
     *
     * @param roleName the value for b_role.role_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}