package com.jzw.book.model;

import java.io.Serializable;

public class Shops implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shop.shop_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shop.shop_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shop.user_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shop.shop_id
     *
     * @return the value of b_shop.shop_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shop.shop_id
     *
     * @param shopId the value for b_shop.shop_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shop.shop_name
     *
     * @return the value of b_shop.shop_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shop.shop_name
     *
     * @param shopName the value for b_shop.shop_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shop.user_id
     *
     * @return the value of b_shop.user_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shop.user_id
     *
     * @param userId the value for b_shop.user_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}