package com.jzw.book.model;

import java.io.Serializable;

public class Types implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_type.type_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_type.type_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_type.type_cli
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    private Integer typeCli;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_type.type_id
     *
     * @return the value of b_type.type_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_type.type_id
     *
     * @param typeId the value for b_type.type_id
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_type.type_name
     *
     * @return the value of b_type.type_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_type.type_name
     *
     * @param typeName the value for b_type.type_name
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_type.type_cli
     *
     * @return the value of b_type.type_cli
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public Integer getTypeCli() {
        return typeCli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_type.type_cli
     *
     * @param typeCli the value for b_type.type_cli
     *
     * @mbg.generated Sun Dec 31 13:41:06 CST 2017
     */
    public void setTypeCli(Integer typeCli) {
        this.typeCli = typeCli;
    }


    @Override
    public String toString() {
        return "Types{" +
                "typeId=" + typeId +
                ", typeName='" + typeName + '\'' +
                ", typeCli=" + typeCli +
                '}';
    }
}